SOURCE: GTA
TARGET: Cityscapes
EXP_NAME : 'GTA2Cityscapes_DeepLabv2_AdvEnt_DS_DP_global_local'
NUM_WORKERS: 4
DATA_DIRECTORY_SOURCE: '<GTA location>'
DATA_DIRECTORY_TARGET : '<Cityscapes location>'
EXP_ROOT : '<Root directory>'
GPU_ID : 2 #-1
CUDA_devices : 'cuda:0,1,2,3'
TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: ../../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  BATCH_SIZE_SOURCE : 0
  BATCH_SIZE_TARGET : 0
  INPUT_SIZE_SOURCE :  [640, 360] # [320, 180]
  INPUT_SIZE_TARGET : [512, 256] #[256, 128] # [128, 64]
  EARLY_STOP :  120000 #/16 40000
  SAVE_PRED_EVERY : 2000 #600 #2000/16
  #LEARNING_RATE_D : 0.00005 #73794699
  MULTI_LEVEL: True

  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best
  INPUT_SIZE_TARGET :  [512,256] #1024, 512) [256, 128]
  OUTPUT_SIZE_TARGET :  [2048,1024] #[1024,512] #[512, 256]
  SNAPSHOT_STEP : 2000
